package by.shestopalov.dbcontroller;

public class SQLHelper {
    public static String REGISTER_QUERY="INSERT USERS(USER_NAME, USER_PASS, USER_ROLE) VALUES(?,?, 0)";
    public static String GET_USER_BY_USERNAME="SELECT * FROM USERS WHERE USER_NAME=?";
    public static String GET_ALL_PRODUCT_CATEGORIES="SELECT * FROM CATEGORY";
    public static String ADD_PRODUCT="INSERT PRODUCTS(PRODUCT_NAME, PRODUCT_CATEGORY_ID, PRODUCT_AMOUNT, PRODUCT_PRICE) VALUES(?,?,?,?)";
    public static String GET_ALL_PRODUCTS="SELECT * FROM PRODUCTS INNER JOIN CATEGORY ON PRODUCTS.PRODUCT_CATEGORY_ID=CATEGORY.CATEGORY_ID";
    public static String GET_PRODUCT_BY_ID="SELECT * FROM PRODUCTS WHERE PRODUCT_ID=?";
    public static String UPDATE_PRODUCT="UPDATE PRODUCTS SET PRODUCT_NAME=?, PRODUCT_CATEGORY_ID=?, PRODUCT_AMOUNT=?, PRODUCT_PRICE=? WHERE PRODUCT_ID=?";

}
